[corrections]
"tour a knit" = "tourniquet"
"tour nick it" = "tourniquet"
"see pee are" = "cpr"
"see pea are" = "cpr"
"hart attack" = "cardiac arrest"
"heart attack" = "cardiac arrest"
"hymlic" = "heimlich"
"hi mlik" = "heimlich"
